<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'days' => [
        1 => 'Lundi',
        2 => 'Mardi',
        3 => 'Mercredi',
        4 => 'Jeudi',
        5 => 'Vendredi',
        6 => 'Samedi',
        7 => 'Dimanche'
    ],

    'months' => [
        1  => 'Janvier',
        2  => 'Février',
        3  => 'Mars',
        4  => 'Avril',
        5  => 'Mai',
        6  => 'Juin',
        7  => 'Juillet',
        8  => 'Août',
        9  => 'Septembre',
        10 => 'Octobre',
        11 => 'Novembre',
        12 => 'Décembre'
    ],

    'months_short' => [
        1  => 'JAN',
        2  => 'FEV',
        3  => 'MAR',
        4  => 'AVR',
        5  => 'MAI',
        6  => 'JUN',
        7  => 'JUL',
        8  => 'AOU',
        9  => 'SEP',
        10 => 'OCT',
        11 => 'NOV',
        12 => 'DÉC'
    ],

    'months_nb' => [
        'JAN' => '01',
        'FEV' => '02',
        'MAR' => '03',
        'AVR' => '04',
        'MAI' => '05',
        'JUN' => '06',
        'JUL' => '07',
        'AOU' => '08',
        'SEP' => '09',
        'OCT' => '10',
        'NOV' => '11',
        'DEC' => '12'
    ]

];
